// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Group struct {
	ent.Schema
}

func (Group) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("id"), field.String("name").Unique().StorageKey("name"), field.String("description").StorageKey("description"), field.Time("createdAt").StorageKey("createdAt"), field.Time("updatedAt").StorageKey("updatedAt")}
}
func (Group) Edges() []ent.Edge {
	return []ent.Edge{edge.To("users", User.Type)}
}
func (Group) Annotations() []schema.Annotation {
	return nil
}
