// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"encoding/json"

	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Keep struct {
	ent.Schema
}

func (Keep) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("id"), field.String("title").StorageKey("title"), field.String("content").StorageKey("content"), field.String("summary").StorageKey("summary"), field.Bool("isPublic").StorageKey("isPublic"), field.JSON("tags", json.RawMessage{}).StorageKey("tags"), field.Int32("views").StorageKey("views"), field.Int32("likes").StorageKey("likes"), field.JSON("extraData", json.RawMessage{}).StorageKey("extraData"), field.String("category").StorageKey("category"), field.String("ownerId").Optional().StorageKey("ownerId"), field.Time("createdAt").StorageKey("createdAt"), field.Time("updatedAt").StorageKey("updatedAt")}

}
func (Keep) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type).Ref("keeps").Unique().Field("ownerId")}
}
func (Keep) Annotations() []schema.Annotation {
	return nil
}
