// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type User struct {
	ent.Schema
}

func (User) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("id"), field.String("email").Unique().StorageKey("email"), field.String("nickname").StorageKey("nickname"), field.String("avatar").StorageKey("avatar"), field.String("bio").StorageKey("bio"), field.Bool("isAdmin").StorageKey("isAdmin"), field.Time("lastLoginAt").StorageKey("lastLoginAt"), field.String("lastLoginIp").StorageKey("lastLoginIp"), field.String("groupId").Optional().StorageKey("groupId"), field.Time("createdAt").StorageKey("createdAt"), field.Time("updatedAt").StorageKey("updatedAt")}
}
func (User) Edges() []ent.Edge {
	return []ent.Edge{edge.To("buckets", Bucket.Type), edge.To("files", File.Type), edge.To("images", Image.Type), edge.To("keeps", Keep.Type), edge.To("mindmaps", Mindmap.Type), edge.To("moments", Moment.Type), edge.To("todos", Todo.Type), edge.From("group", Group.Type).Ref("users").Unique().Field("groupId"), edge.To("videos", Video.Type)}
}
func (User) Annotations() []schema.Annotation {
	return nil
}
