// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"api.us4ever/internal/ent/mindmap"
	"api.us4ever/internal/ent/user"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MindmapCreate is the builder for creating a Mindmap entity.
type MindmapCreate struct {
	config
	mutation *MindmapMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (mc *MindmapCreate) SetTitle(s string) *MindmapCreate {
	mc.mutation.SetTitle(s)
	return mc
}

// SetContent sets the "content" field.
func (mc *MindmapCreate) SetContent(jm json.RawMessage) *MindmapCreate {
	mc.mutation.SetContent(jm)
	return mc
}

// SetSummary sets the "summary" field.
func (mc *MindmapCreate) SetSummary(s string) *MindmapCreate {
	mc.mutation.SetSummary(s)
	return mc
}

// SetIsPublic sets the "isPublic" field.
func (mc *MindmapCreate) SetIsPublic(b bool) *MindmapCreate {
	mc.mutation.SetIsPublic(b)
	return mc
}

// SetTags sets the "tags" field.
func (mc *MindmapCreate) SetTags(jm json.RawMessage) *MindmapCreate {
	mc.mutation.SetTags(jm)
	return mc
}

// SetViews sets the "views" field.
func (mc *MindmapCreate) SetViews(i int32) *MindmapCreate {
	mc.mutation.SetViews(i)
	return mc
}

// SetLikes sets the "likes" field.
func (mc *MindmapCreate) SetLikes(i int32) *MindmapCreate {
	mc.mutation.SetLikes(i)
	return mc
}

// SetExtraData sets the "extraData" field.
func (mc *MindmapCreate) SetExtraData(jm json.RawMessage) *MindmapCreate {
	mc.mutation.SetExtraData(jm)
	return mc
}

// SetCategory sets the "category" field.
func (mc *MindmapCreate) SetCategory(s string) *MindmapCreate {
	mc.mutation.SetCategory(s)
	return mc
}

// SetOwnerId sets the "ownerId" field.
func (mc *MindmapCreate) SetOwnerId(s string) *MindmapCreate {
	mc.mutation.SetOwnerId(s)
	return mc
}

// SetNillableOwnerId sets the "ownerId" field if the given value is not nil.
func (mc *MindmapCreate) SetNillableOwnerId(s *string) *MindmapCreate {
	if s != nil {
		mc.SetOwnerId(*s)
	}
	return mc
}

// SetCreatedAt sets the "createdAt" field.
func (mc *MindmapCreate) SetCreatedAt(t time.Time) *MindmapCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetUpdatedAt sets the "updatedAt" field.
func (mc *MindmapCreate) SetUpdatedAt(t time.Time) *MindmapCreate {
	mc.mutation.SetUpdatedAt(t)
	return mc
}

// SetID sets the "id" field.
func (mc *MindmapCreate) SetID(s string) *MindmapCreate {
	mc.mutation.SetID(s)
	return mc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (mc *MindmapCreate) SetUserID(id string) *MindmapCreate {
	mc.mutation.SetUserID(id)
	return mc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (mc *MindmapCreate) SetNillableUserID(id *string) *MindmapCreate {
	if id != nil {
		mc = mc.SetUserID(*id)
	}
	return mc
}

// SetUser sets the "user" edge to the User entity.
func (mc *MindmapCreate) SetUser(u *User) *MindmapCreate {
	return mc.SetUserID(u.ID)
}

// Mutation returns the MindmapMutation object of the builder.
func (mc *MindmapCreate) Mutation() *MindmapMutation {
	return mc.mutation
}

// Save creates the Mindmap in the database.
func (mc *MindmapCreate) Save(ctx context.Context) (*Mindmap, error) {
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MindmapCreate) SaveX(ctx context.Context) *Mindmap {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MindmapCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MindmapCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MindmapCreate) check() error {
	if _, ok := mc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Mindmap.title"`)}
	}
	if _, ok := mc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Mindmap.content"`)}
	}
	if _, ok := mc.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "Mindmap.summary"`)}
	}
	if _, ok := mc.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "isPublic", err: errors.New(`ent: missing required field "Mindmap.isPublic"`)}
	}
	if _, ok := mc.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Mindmap.tags"`)}
	}
	if _, ok := mc.mutation.Views(); !ok {
		return &ValidationError{Name: "views", err: errors.New(`ent: missing required field "Mindmap.views"`)}
	}
	if _, ok := mc.mutation.Likes(); !ok {
		return &ValidationError{Name: "likes", err: errors.New(`ent: missing required field "Mindmap.likes"`)}
	}
	if _, ok := mc.mutation.ExtraData(); !ok {
		return &ValidationError{Name: "extraData", err: errors.New(`ent: missing required field "Mindmap.extraData"`)}
	}
	if _, ok := mc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "Mindmap.category"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Mindmap.createdAt"`)}
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Mindmap.updatedAt"`)}
	}
	return nil
}

func (mc *MindmapCreate) sqlSave(ctx context.Context) (*Mindmap, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Mindmap.ID type: %T", _spec.ID.Value)
		}
	}
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MindmapCreate) createSpec() (*Mindmap, *sqlgraph.CreateSpec) {
	var (
		_node = &Mindmap{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(mindmap.Table, sqlgraph.NewFieldSpec(mindmap.FieldID, field.TypeString))
	)
	if id, ok := mc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := mc.mutation.Title(); ok {
		_spec.SetField(mindmap.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := mc.mutation.Content(); ok {
		_spec.SetField(mindmap.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if value, ok := mc.mutation.Summary(); ok {
		_spec.SetField(mindmap.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := mc.mutation.IsPublic(); ok {
		_spec.SetField(mindmap.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := mc.mutation.Tags(); ok {
		_spec.SetField(mindmap.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := mc.mutation.Views(); ok {
		_spec.SetField(mindmap.FieldViews, field.TypeInt32, value)
		_node.Views = value
	}
	if value, ok := mc.mutation.Likes(); ok {
		_spec.SetField(mindmap.FieldLikes, field.TypeInt32, value)
		_node.Likes = value
	}
	if value, ok := mc.mutation.ExtraData(); ok {
		_spec.SetField(mindmap.FieldExtraData, field.TypeJSON, value)
		_node.ExtraData = value
	}
	if value, ok := mc.mutation.Category(); ok {
		_spec.SetField(mindmap.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(mindmap.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mc.mutation.UpdatedAt(); ok {
		_spec.SetField(mindmap.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := mc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mindmap.UserTable,
			Columns: []string{mindmap.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MindmapCreateBulk is the builder for creating many Mindmap entities in bulk.
type MindmapCreateBulk struct {
	config
	err      error
	builders []*MindmapCreate
}

// Save creates the Mindmap entities in the database.
func (mcb *MindmapCreateBulk) Save(ctx context.Context) ([]*Mindmap, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Mindmap, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MindmapMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MindmapCreateBulk) SaveX(ctx context.Context) []*Mindmap {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MindmapCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MindmapCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
