// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Video struct {
	ent.Schema
}

func (Video) Fields() []ent.Field {
	return []ent.Field{field.String("id"), field.String("name"), field.String("type"), field.Int("size"), field.String("hash"), field.Int32("duration"), field.Bool("isPublic"), field.JSON("extraData", struct{}{}), field.String("category"), field.String("posterId").Optional(), field.String("fileId").Optional(), field.String("uploadedBy").Optional(), field.Time("createdAt"), field.Time("updatedAt")}

}
func (Video) Annotations() []schema.Annotation {
	return nil
}
func (Video) Edges() []ent.Edge {
	return []ent.Edge{edge.To("moment_videos", MomentVideo.Type), edge.From("video_file", File.Type).Ref("video_file").Unique().Field("fileId"), edge.From("video_poster", File.Type).Ref("video_poster").Unique().Field("posterId"), edge.From("user", User.Type).Ref("videos").Unique().Field("uploadedBy")}
}
